version: '3.7'

services:

  hello-world:
    container_name: vue-hello-world
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3002:8080
    environment:
      - CHOKIDAR_USEPOLLING=true 
    stdin_open: true  